
import { Article, NavLink, CommunityPost, Author, AffiliateCategory, BornInAmericaProduct, VideoSource } from './types';
import { 
    UsersIcon, 
    NewspaperIcon, 
    InformationCircleIcon, 
    ChatBubbleLeftEllipsisIcon, 
    ShieldCheckIcon,
    CurrencyDollarIcon,
    LockClosedIcon,
    HeartIcon,
    BuildingStorefrontIcon,
    WifiIcon,
    PresentationChartLineIcon,
    PlayCircleIcon,
    XMarkIcon,
    SparklesIcon
} from './components/icons/FluentIcons';

export const SITE_TITLE = "TheSaveUSA.com";
export const TAGLINE = "AMERICA FIRST NEWS & COMMENTARY";
export const NETWORK_TAGLINE = "The Patriot Network Hub";

export enum SitePages {
  Home = "/home",
  About = "/about",
  Politics = "/politics",
  Opinion = "/opinion",
  Culture = "/culture",
  ElectionIntegrity = "/election-integrity",
  Article = "/article", // Base path for article detail pages
  CommunityVoices = "/community-voices",
  RecommendedResources = "/resources",
  SupportUs = "/support-us", // New Page
}

export const NAV_LINKS: NavLink[] = [
  { name: "Home", path: SitePages.Home, icon: NewspaperIcon },
  { name: "Politics", path: SitePages.Politics, isCategory: true, icon: UsersIcon },
  { name: "Opinion", path: SitePages.Opinion, isCategory: true, icon: ChatBubbleLeftEllipsisIcon },
  { name: "Culture Wars", path: SitePages.Culture, isCategory: true, icon: ShieldCheckIcon },
  { name: "Election Integrity", path: SitePages.ElectionIntegrity, isCategory: true, icon: ShieldCheckIcon },
  { name: "Community Voices", path: SitePages.CommunityVoices, icon: UsersIcon },
  { name: "Born in America", path: `${SitePages.RecommendedResources}#born-in-america-marketplace`, icon: SparklesIcon },
  { name: "Resources", path: SitePages.RecommendedResources, icon: PresentationChartLineIcon },
  { name: "Support Us", path: SitePages.SupportUs, icon: HeartIcon }, // New Link
  { name: "About Us", path: SitePages.About, icon: InformationCircleIcon },
];

export const CATEGORIES: string[] = NAV_LINKS.filter(link => link.isCategory).map(link => link.name);

// Centralized Author Profiles
export const AUTHORS: Record<string, Author> = {
  patriotWriter: {
    id: "author01",
    name: "John D. Patriot",
    bio: "A veteran journalist with 20 years of experience, John is dedicated to uncovering the truth the mainstream media ignores.",
    avatarSeed: "johnD"
  },
  familyDefender: {
    id: "author02",
    name: "Susan B. Anthony",
    bio: "A concerned mother and community organizer, Susan fights on the frontlines of the culture war to protect our children and traditional values.",
    avatarSeed: "susanB"
  },
  veritasMaximus: {
    id: "author03",
    name: "Veritas Maximus",
    bio: "An anonymous watchdog committed to exposing corruption and advocating for electoral transparency. The truth has a name.",
    avatarSeed: "veritasM"
  },
  magaHistorian: {
    id: "author04",
    name: "George Washington",
    bio: "A historian specializing in the populist movement, George documents the achievements and legacy of the 'America First' agenda.",
    avatarSeed: "georgeW"
  },
  borderHawk: {
    id: "author05",
    name: "Samuel 'Hawk' Johnson",
    bio: "With years of on-the-ground experience at the southern border, 'Hawk' provides unparalleled insight into the immigration crisis.",
    avatarSeed: "samuelJ"
  },
  evelynReed: {
    id: "author06",
    name: "Dr. Evelyn Reed",
    bio: "An economist who argues that national prosperity is built on protectionism, not globalism. Dr. Reed is a fierce critic of free trade agreements.",
    avatarSeed: "evelynR"
  },
  markJustice: {
    id: "author07",
    name: "Mark 'Scales' Justice",
    bio: "A former federal prosecutor who now dedicates his time to exposing the weaponization of the justice system and defending the Constitution.",
    avatarSeed: "markJ"
  },
};


export const SAMPLE_ARTICLES: Article[] = [
  {
    id: "defund-un-threat",
    title: "Defund and Exit: Why the UN is a Threat to American Sovereignty",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "November 20, 2023",
    summary: "The United Nations was sold as a beacon of peace, but it has become a bloated bureaucracy pushing a globalist agenda that undermines American freedom and sovereignty. It's time to pull the plug.",
    content: `<p class="mb-4">The United Nations headquarters in New York stands as a monument to a failed globalist experiment. We were promised an institution that would prevent war and promote human rights. Instead, we got a taxpayer-funded club for dictators and a platform for anti-American sentiment. From its climate alarmism to its attacks on national sovereignty, the UN actively works against the interests of the United States.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">America Pays the Price</h2><p class="mb-4">American taxpayers are the single largest contributors to the UN budget, yet we receive nothing but contempt in return. Our money funds resolutions that condemn our allies, promotes ideologies that are hostile to our way of life, and props up corrupt regimes. It's a bad deal, and it's time for it to end. The concept of an 'Amerexit'—an American exit from the UN—is no longer a fringe idea; it's a necessity for national survival.</p><p class="mt-6 italic">Let's stop funding the organization that seeks to undermine us. It's time to put America First, not the interests of unelected global bureaucrats.</p>`,
    imageUrl: "https://picsum.photos/seed/unbuilding/600/400",
    keywords: ["UN", "United Nations", "sovereignty", "globalism", "america first", "foreign policy"],
    tone: "critical",
  },
  {
    id: "poison-ivy-league",
    title: "Poison Ivy: How Our Universities Became Marxist Indoctrination Camps",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "November 19, 2023",
    summary: "Once revered institutions of higher learning are now assembly lines for radical leftism, churning out graduates who hate America. How did this happen, and what can parents do?",
    content: `<p class="mb-4">Parents save for decades to send their children to college, hoping they'll receive an education that prepares them for a successful future. Instead, they're paying exorbitant tuition fees for their kids to be indoctrinated by radical-left professors in subjects like 'gender studies' and 'critical race theory.' These universities have become hostile environments for conservative thought, where free speech is silenced and students are taught to be ashamed of their country.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Grievance-Industrial Complex</h2><p class="mb-4">Higher education is no longer about the pursuit of knowledge; it's about the manufacturing of grievance. Students are taught to see everything through the lens of oppression, to tear down statues, and to demand 'safe spaces' from differing opinions. The result is a generation of fragile, entitled activists who are unprepared for the real world and filled with contempt for the nation that gave them so much opportunity.</p><p class="mt-6 italic">It's time for parents to defund these institutions. Consider trade schools, community colleges, or universities that haven't been corrupted by the woke mind virus. The future of our nation depends on it.</p>`,
    imageUrl: "https://picsum.photos/seed/universitycampus/600/400",
    keywords: ["higher education", "college", "universities", "indoctrination", "woke", "free speech", "culture war"],
    tone: "urgent",
  },
  {
    id: "battle-for-the-courts",
    title: "The Battle for the Courts: Appointing Constitutionalist Judges is Non-Negotiable",
    category: "Politics",
    author: AUTHORS.markJustice,
    date: "November 18, 2023",
    summary: "The longest-lasting legacy of any president is their judicial appointments. Activist judges legislate from the bench, but constitutionalists preserve our Republic. This is a fight we can't afford to lose.",
    content: `<p class="mb-4">Forget the daily news cycle. The most consequential battle for America's future is being fought over the judiciary. For decades, the left has successfully installed activist judges who believe in a 'living Constitution'—a document they can twist and contort to fit their political agenda. This is a direct assault on the rule of law and the will of the people.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Originalism: The Only Defense</h2><p class="mb-4">The only antidote to this judicial activism is the appointment of constitutionalists—judges who understand that their job is to interpret the law as it was written, not as they wish it were. These judges, often called originalists or textualists, are the last line of defense for our God-given rights, including the Second Amendment, religious freedom, and free speech. The Trump administration's success in appointing hundreds of these judges was one of its greatest achievements.</p><p class="mt-6 italic">Every election is a battle for the courts. We must elect leaders who are committed to appointing strong constitutionalists and confirm them at every level. The soul of the Republic is at stake.</p>`,
    imageUrl: "https://picsum.photos/seed/courthouse/600/400",
    keywords: ["judges", "supreme court", "constitution", "judicial appointments", "originalism", "legal"],
    tone: "urgent",
  },
  {
    id: "globalism-last-gasp",
    title: "Globalism's Last Gasp: Why Tariffs and Trade Walls Build National Wealth",
    category: "Opinion",
    author: AUTHORS.evelynReed,
    date: "November 17, 2023",
    summary: "For decades, we were told that globalism and 'free trade' would bring prosperity. Instead, it gutted our manufacturing base and enriched China. The path to wealth is through economic nationalism.",
    content: `<p class="mb-4">The globalist elites in Washington, on Wall Street, and in academia sold us a bill of goods. They promised that 'free trade' agreements like NAFTA and opening trade with China would lead to a new era of prosperity. For them, it did. For the American worker, it was a disaster. We watched as our factories were shuttered and our jobs were shipped overseas, all in the name of cheap goods and corporate profits.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Economic Nationalism is Common Sense</h2><p class="mb-4">An 'America First' economic policy isn't a radical idea; it's how great nations have always been built. Using tariffs to protect our domestic industries, encouraging companies to manufacture here, and prioritizing American workers is the only path to sustainable, long-term prosperity. A nation that cannot feed, clothe, and arm itself is not a sovereign nation. It is dependent on the whims of its adversaries.</p><p class="mt-6 italic">We need to rebuild our factories, reshore our supply chains, and put an end to the globalist project once and for all. A nation's wealth is its people and its production, not its ability to import cheap junk from China.</p>`,
    imageUrl: "https://picsum.photos/seed/cargoship/600/400",
    keywords: ["globalism", "tariffs", "trade", "economy", "protectionism", "made in america", "nationalism"],
    tone: "praising",
  },
  {
    id: "voter-id-reform",
    title: "Voter ID: The Simple, Common-Sense Reform the Left Calls 'Racist'",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "November 16, 2023",
    summary: "You need an ID to buy beer, board a plane, or enter a federal building. So why does the left have a meltdown over requiring one to vote? The answer is simple: they want to make it easier to cheat.",
    content: `<p class="mb-4">In the fight for election integrity, no issue is more straightforward than voter ID. A vast majority of Americans, across all demographics, support the common-sense requirement to show a photo ID to vote. It is the simplest, most effective way to prevent impersonation fraud and increase public confidence in our elections. So why is it so controversial?</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Phony Outrage</h2><p class="mb-4">The left's argument that voter ID laws are 'discriminatory' or 'suppressive' is a bad-faith smear. They know that these laws are not a barrier to legitimate voting. In a world where photo IDs are required for countless everyday activities, the idea that obtaining one is an insurmountable hurdle is absurd. Their real opposition is not based on principle; it's based on politics. They believe that lax election rules benefit them, and they are willing to sacrifice election security to gain a partisan advantage.</p><p class="mt-6 italic">Don't fall for the lies. Voter ID is about one thing: ensuring that every legal vote is counted, and that illegal votes are not. It's the cornerstone of a trustworthy election system.</p>`,
    imageUrl: "https://picsum.photos/seed/voterid/600/400",
    keywords: ["voter id", "election integrity", "fraud", "secure elections", "common sense"],
    tone: "skeptical",
  },
  {
    id: "nuclear-family-hope",
    title: "The Nuclear Family: America's Last Best Hope",
    category: "Opinion",
    author: AUTHORS.familyDefender,
    date: "November 15, 2023",
    summary: "A strong nation is built on strong families. The relentless attack on the traditional nuclear family is no coincidence; it's a deliberate strategy to weaken America from within. It's time to rebuild.",
    content: `<p class="mb-4">Look at the biggest problems plaguing our society: crime, poverty, mental illness. At the root of so many of them, you will find the collapse of the family. For generations, the nuclear family—a married mother and father raising their children—was the bedrock of our civilization. It is the most effective institution for raising healthy, well-adjusted, and productive citizens. The left knows this, which is why they have worked so hard to destroy it.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">A Deliberate Demolition</h2><p class="mb-4">Through welfare policies that penalize marriage, a culture that celebrates promiscuity, and an education system that undermines parental authority, the left has waged a multi-generational war on the family. They want to replace the family with the State, making citizens dependent on the government from cradle to grave. A society without strong families is a society that is easy to control.</p><p class="mt-6 italic">The most patriotic thing you can do is build a strong family. We must defend the traditional family unit as if the future of our country depends on it—because it does.</p>`,
    imageUrl: "https://picsum.photos/seed/happyfamily/600/400",
    keywords: ["family", "nuclear family", "traditional values", "culture", "society", "children"],
    tone: "praising",
  },
  {
    id: "sports-patriotism-decline",
    title: "From Anthem to Apology: The Decline of Patriotism in Pro Sports",
    category: "Opinion",
    author: AUTHORS.magaHistorian,
    date: "November 14, 2023",
    summary: "Professional sports leagues, once a source of national unity, have become platforms for anti-American protests and woke politics. What happened to loving your country?",
    content: `<p class="mb-4">Not long ago, a professional sports game was a unifying event. People from all walks of life came together to cheer for their team, and standing for the National Anthem was a moment of shared pride. Today, many leagues have transformed their fields and courts into stages for political protest, often denigrating the very flag that represents the freedoms they enjoy. The millionaire athletes lecture the working-class fans about their supposed privilege, and the leagues they play for bow to woke pressure.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">'Get Woke, Go Broke' is More Than a Slogan</h2><p class="mb-4">Fans are getting tired of being preached to. They watch sports to escape politics, not to be lectured by them. The declining ratings and empty seats for some leagues prove that when you insult your customer base, they will tune out. It's time for these organizations to remember that patriotism is not a political statement; it's a unifying value.</p><p class="mt-6 italic">We want sports, not sociology lectures. We want to see love of country, not contempt for it. Maybe it's time to turn off the TV and go play catch in the backyard instead.</p>`,
    imageUrl: "https://picsum.photos/seed/kneelingplayer/600/400",
    keywords: ["sports", "patriotism", "national anthem", "woke", "cancel culture", "NFL", "NBA"],
    tone: "critical",
  },
  {
    id: "bring-jobs-home",
    title: "Made in America Again: It's Not a Slogan, It's Our Survival",
    category: "Opinion",
    author: AUTHORS.patriotWriter,
    date: "November 13, 2023",
    summary: "For decades, our leaders sold out American workers for cheap foreign labor. It's time for a manufacturing renaissance that puts American jobs and national security first.",
    content: `<p class="mb-4">The Rust Belt is not just a place; it's a scar on the American landscape, a testament to decades of betrayal by our political and corporate elites. They chased cheap labor in China and elsewhere, hollowed out our industrial heartland, and told us to 'learn to code.' They traded our national security and economic independence for corporate profits. The America First movement was born from the ashes of this great betrayal.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">A Manufacturing Renaissance</h2><p class="mb-4">Bringing manufacturing back to the USA is not about nostalgia; it's about survival. It's about secure supply chains for essential goods. It's about providing high-paying, dignified work for American citizens. It's about rebuilding our middle class and our national pride. We can and must compete. Through smart trade policy, deregulation, and celebrating American craftsmanship, we can spark a new industrial revolution.</p><p class="mt-6 italic">Let's build things here again. Let's stamp 'Made in the USA' on the future. Our prosperity and security depend on it.</p>`,
    imageUrl: "https://picsum.photos/seed/usfactory/600/400",
    keywords: ["made in america", "manufacturing", "jobs", "economy", "national security", "supply chain"],
    tone: "praising",
  },
  {
    id: "doj-weaponized",
    title: "Two-Tiered Justice? DOJ Under Fire for Perceived Political Bias",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "November 12, 2023",
    summary: "Allegations of selective prosecution and political targeting are shaking public trust in the Department of Justice. Is America's legal system being weaponized?",
    content: `<p class="mb-4">The sacred principle of "equal justice under law" is facing its greatest threat in modern American history. A growing number of citizens believe the Department of Justice and the FBI are no longer impartial arbiters of the law, but have become political weapons wielded by the ruling party against its opponents. The evidence is becoming too glaring to ignore.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Selective Justice on Display</h2><p class="mb-4">We see investigations into one political party that drag on for years with endless resources, while scandals involving the other party are swept under the rug or closed with a whimper. This two-tiered system erodes the very foundation of our Republic. When the law is applied differently based on political affiliation, it ceases to be law and becomes a tool of oppression.</p><p class="mt-6 italic">Restoring faith in our institutions requires a complete cleaning of house. We must demand accountability and an end to the political weaponization of our justice system before it's too late.</p>`,
    imageUrl: "https://picsum.photos/seed/justicebalance/600/400",
    keywords: ["DOJ", "justice system", "political bias", "two-tiered justice", "weaponization"],
    tone: "critical",
  },
  {
    id: "ev-mandate-madness",
    title: "The EV Mandate Madness: A Costly Green Fantasy",
    category: "Politics",
    author: AUTHORS.borderHawk,
    date: "November 11, 2023",
    summary: "The government's aggressive push for Electric Vehicles ignores the massive costs, infrastructure challenges, and reliance on foreign adversaries. Who really benefits?",
    content: `<p class="mb-4">The elites in Washington and California are determined to force every American into an electric vehicle, whether they want one or not. They sell it as a green utopia, but the reality is a logistical and economic nightmare for the middle class. These EV mandates are disconnected from reality, costly for consumers, and dangerously beneficial to our primary adversary: China.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Hidden Costs and Dangers</h2><p class="mb-4">EVs are expensive, our power grid can't handle the increased demand, and the raw materials for batteries are largely controlled by China. Every EV mandate deepens our dependence on a hostile foreign power for our transportation needs. Furthermore, they are ignoring the environmental damage caused by mining for these materials. It's not about the environment; it's about control and enriching a select few.</p><p class="mt-6 italic">American freedom includes the freedom to choose the car that best suits your family's needs. We need energy policies that promote American independence, not pipe dreams that empower our enemies.</p>`,
    imageUrl: "https://picsum.photos/seed/evcharging/600/400",
    keywords: ["EV", "electric vehicles", "green energy", "mandates", "China", "energy policy"],
    tone: "skeptical",
  },
  {
    id: "digital-parenting",
    title: "Digital Battleground: Protecting Your Kids in a Woke Online World",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "November 10, 2023",
    summary: "From social media algorithms to streaming shows, our children are being bombarded with radical ideologies. Here’s how parents can build a digital defense.",
    content: `<p class="mb-4">The internet can be a wonderful tool, but it has also become the primary vector for radical indoctrination targeting our children. From TikTok trends that promote dangerous behavior to streaming cartoons that push gender ideology, the digital world is a minefield for parents trying to raise kids with traditional values. We can no longer afford to be passive.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Building Your Family's Digital Fortress</h2><p class="mb-4">Active monitoring, content filters, and open conversations are essential. But more than that, we must proactively provide our children with positive, pro-American content. We need to build a parallel culture that celebrates our heritage and values, giving them a strong foundation to resist the onslaught of woke propaganda. It's a daily battle, and we must be armed for it.</p><p class="mt-6 italic">Protecting our children's innocence and their minds is the most important frontline in the culture war. It's a fight we cannot afford to lose.</p>`,
    imageUrl: "https://picsum.photos/seed/familycomputer/600/400",
    keywords: ["parenting", "children", "online safety", "social media", "woke media", "indoctrination"],
    tone: "urgent",
  },
  {
    id: "save-christmas",
    title: "The War on Christmas is Real: Reclaiming Our Sacred Traditions",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "November 09, 2023",
    summary: "It's not just 'Happy Holidays.' There's a deliberate effort to erase the true meaning of Christmas. It's time to stand up for our faith and traditions.",
    content: `<p class="mb-4">You see it everywhere. The generic "Happy Holidays" greeting, the sterile "Winter Festival," the deliberate avoidance of the word "Christmas." This is not an act of inclusion; it is a calculated effort to strip a sacred Christian holiday of its meaning and to slowly erase our nation's Christian heritage from the public square. The war on Christmas is real, and it's part of the broader war on our values.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Merry Christmas! Say It Loud!</h2><p class="mb-4">We must not be ashamed to celebrate the birth of Jesus Christ. We should embrace our traditions with joy and confidence. Decorate our homes, sing our carols, and wish our neighbors a "Merry Christmas" without hesitation. By openly celebrating, we push back against the secular tide and remind the world that this is a nation built on faith. It's a simple act of defiance that carries immense cultural weight.</p><p class="mt-6 italic">Let's not just keep Christ in Christmas; let's proclaim it. The soul of our nation may depend on it.</p>`,
    imageUrl: "https://picsum.photos/seed/christmasdecor/600/400",
    keywords: ["Christmas", "tradition", "faith", "Christianity", "war on christmas", "values"],
    tone: "praising",
  },
  {
    id: "poll-watchers-needed",
    title: "Eyes on the Count: Why Poll Watchers Are Our Last Line of Defense",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "November 08, 2023",
    summary: "Transparency in elections isn't given, it's demanded. Learn why the role of the citizen poll watcher is more critical now than ever before for ensuring fair elections.",
    content: `<p class="mb-4">The phrase "election integrity" is meaningless without transparency. And transparency isn't possible without citizen oversight. In the complex and often chaotic process of an election, the humble poll watcher is a critical safeguard against error, incompetence, and outright fraud. They are the eyes and ears of the people, ensuring the process is run according to law.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Your Country Needs You at the Polls</h2><p class="mb-4">Being a poll watcher is a direct, impactful way to serve your country. It requires attention to detail, a calm demeanor, and a commitment to fairness. By observing the process, documenting irregularities, and asking questions, you become an active participant in safeguarding our democracy. The left often demonizes poll watchers because they fear the scrutiny. That's exactly why we need more of them.</p><p class="mt-6 italic">Don't just vote. Get involved. Become a poll watcher and be a guardian of the ballot box.</p>`,
    imageUrl: "https://picsum.photos/seed/pollwatcher/600/400",
    keywords: ["poll watcher", "election integrity", "transparency", "volunteers", "secure elections"],
    tone: "urgent",
  },
  {
    id: "misinformation-label",
    title: "The 'Misinformation' Smokescreen: How They Censor Truth About Elections",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "November 07, 2023",
    summary: "Any question about election anomalies is immediately labeled 'misinformation.' This isn't about protecting you; it's about controlling you and shutting down legitimate debate.",
    content: `<p class="mb-4">It's the ultimate conversation-stopper. The moment you raise a legitimate question about election anomalies, ballot chain of custody, or outdated voter rolls, you are slapped with the "misinformation" label. This tactic, wielded by Big Tech and the mainstream media, is not designed to foster accuracy; it's designed to enforce silence and protect the official narrative at all costs.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Censorship Disguised as Fact-Checking</h2><p class="mb-4">This 'Ministry of Truth' decides what you are allowed to see and say. Legitimate statistical analysis is called a 'conspiracy theory.' Eyewitness affidavits are dismissed as 'anecdotal.' This is a dangerous game. By censoring debate, they are not only infringing on our First Amendment rights but also breeding deep distrust in the system. If everything is fair and transparent, why are they so afraid of questions?</p><p class="mt-6 italic">We must resist the censors. We must continue to ask the hard questions and demand the truth. Free and open debate is the only path to restoring faith in our elections.</p>`,
    imageUrl: "https://picsum.photos/seed/censored/600/400",
    keywords: ["censorship", "misinformation", "free speech", "big tech", "election debate"],
    tone: "skeptical",
  },
  {
    id: "biden-economy-fail",
    title: "Biden's Economic Policies: A Disaster for Working Americans?",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "October 26, 2023",
    summary: "Inflation soars and jobs vanish under the current administration's radical agenda. We dive deep into the numbers the mainstream media won't show you.",
    content: `<p class="mb-4">The American dream is turning into a nightmare for many, thanks to the disastrous economic policies of the Biden administration. Skyrocketing inflation, stagnant wages, and an uncertain job market are the new reality. Mainstream media outlets, beholden to their globalist puppet masters, paint a rosy picture, but everyday Americans know the truth.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Inflation Nightmare</h2><p class="mb-4">From the gas pump to the grocery store, prices are out of control. The so-called 'transitory' inflation has become a permanent fixture, eroding the purchasing power of hardworking families. This isn't accidental; it's a direct result of reckless government spending and anti-growth regulations.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Job Security: A Thing of the Past?</h2><p class="mb-4">While the administration boasts about job numbers, the quality of these jobs and the security they offer are questionable. Small businesses, the backbone of our economy, are struggling under the weight of new mandates and a hostile economic environment. We need to return to policies that empower job creators, not stifle them.</p><p class="mt-6 italic">It's time for a change. It's time to put America First again and restore economic sanity before it's too late.</p>`,
    imageUrl: "https://picsum.photos/seed/concernedfamily/600/400",
    keywords: ["economy", "biden", "inflation", "jobs", "radical left"],
    tone: "critical",
  },
  {
    id: "culture-war-frontlines",
    title: "The Woke Agenda Invades Our Schools: Parents Fight Back!",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "October 25, 2023",
    summary: "Radical ideologies are poisoning the minds of our children. Brave parents are standing up to school boards and demanding a return to traditional values.",
    content: `<p class="mb-4">Our schools, once bastions of learning and critical thinking, have become battlegrounds in the culture war. The 'Woke' agenda, pushed by radical activists and out-of-touch bureaucrats, seeks to indoctrinate our children with divisive and dangerous ideologies. Critical Race Theory, gender ideology, and anti-American sentiment are being forced into curricula, often without parental consent.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Parents on the Frontlines</h2><p class="mb-4">Across the nation, courageous parents are making their voices heard. They are attending school board meetings, challenging harmful policies, and demanding transparency. This is not about hate; it's about protecting our children and preserving the values that made this country great.</p><img src="https://picsum.photos/seed/parentprotest/600/350" alt="Parents protesting" class="my-4 rounded shadow-lg mx-auto" /><p class="mb-4">The fight for the soul of our education system is far from over. We must support these parent warriors and ensure that our schools focus on academic excellence and true American history, not leftist propaganda.</p><p class="mt-6 italic">The future of our children, and our nation, depends on it.</p>`,
    imageUrl: "https://picsum.photos/seed/determinedparents/600/400",
    keywords: ["woke", "schools", "parents", "crt", "traditional values"],
    tone: "urgent",
  },
    {
    id: "2a-under-assault",
    title: "They're Coming for Your Guns: The Left's New Assault on the Second Amendment",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "October 29, 2023",
    summary: "A look at recent legislative proposals and rhetoric that gun owners see as a direct threat to their constitutional rights. This is a battle for the soul of America.",
    content: `<p class="mb-4">Make no mistake, the radical left's ultimate goal is the complete disarmament of the American people. Hiding behind the guise of 'common-sense gun safety,' they are chipping away at our God-given right to keep and bear arms, as enshrined in the Second Amendment. Every new proposal, from 'assault weapon' bans to red flag laws, is another step towards tyranny.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Fallacy of 'Gun Control'</h2><p class="mb-4">The simple truth is that gun control laws only disarm law-abiding citizens. Criminals, by their very nature, do not follow laws. These measures leave honest people defenseless against those who wish to do them harm. The founders knew that an armed populace is the ultimate check against a tyrannical government, and that is precisely why the left is so desperate to take our firearms.</p><p class="mt-6 italic">We cannot give an inch. The right to self-defense is not negotiable. Every patriot must be ready to defend the Second Amendment as if their life, and the life of the Republic, depends on it—because it does.</p>`,
    imageUrl: "https://picsum.photos/seed/gunrights/600/400",
    keywords: ["2A", "gun control", "second amendment", "tyranny", "self-defense"],
    tone: "urgent",
  },
  {
    id: "election-integrity-now",
    title: "Election Integrity: The Unspoken Crisis Threatening Our Republic",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "October 24, 2023",
    summary: "Questions surrounding recent elections persist. Why the silence from the media? We explore the urgent need for transparent and secure voting systems.",
    content: `<p class="mb-4">The bedrock of any constitutional republic is free and fair elections. Yet, in recent times, serious questions have been raised about the integrity of our electoral processes. These concerns are not 'conspiracy theories,' as the mainstream media would have you believe; they are legitimate inquiries from citizens who demand accountability and transparency.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Media Blackout</h2><p class="mb-4">Why is there such a concerted effort to silence any discussion about election irregularities? Why are patriots who voice concerns labeled and censored? This suppression of dissent is a hallmark of authoritarian regimes, not a healthy democracy. We must demand answers and investigate all credible allegations.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Path to Secure Elections</h2><ul class="list-disc list-inside mb-4 pl-4 space-y-1"><li>Voter ID for all elections.</li><li>Paper ballots and robust audits.</li><li>Clean voter rolls, removing deceased and ineligible voters.</li><li>Strict limits on mail-in voting and ballot harvesting.</li></ul><p class="mb-4">Implementing common-sense reforms is not voter suppression; it's voter protection. It ensures that every legal vote counts and that the voice of the American people is heard accurately.</p><p class="mt-6 italic">Without trustworthy elections, we don't have a country. The fight for election integrity is a fight for America itself.</p>`,
    imageUrl: "https://picsum.photos/seed/votingline/600/400",
    keywords: ["election integrity", "voter fraud", "secure elections", "deep state"],
    tone: "skeptical",
  },
  {
    id: "trump-legacy",
    title: "Revisiting the Trump Era: A Time of Strength and Prosperity",
    category: "Opinion",
    author: AUTHORS.magaHistorian,
    date: "October 23, 2023",
    summary: "Despite relentless attacks, the Trump presidency delivered on its promises: a booming economy, secure borders, and a renewed sense of national pride. We remember the achievements.",
    content: `<p class="mb-4">In an era of political correctness and globalist agendas, Donald J. Trump's presidency stands as a testament to what 'America First' policies can achieve. Derided by the establishment and relentlessly attacked by a biased media, his administration nevertheless delivered unprecedented results for the American people.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Economic Boom</h2><p class="mb-4">Tax cuts, deregulation, and fair trade deals unleashed the American economy. Unemployment reached historic lows across all demographics. Manufacturing jobs, long outsourced, began to return to our shores. This wasn't 'trickle-down' economics; it was 'Middle-Class Boom' economics.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Secure Borders, Strong Nation</h2><p class="mb-4">A nation without borders is not a nation. President Trump understood this fundamental truth. He fought to secure our southern border, crack down on illegal immigration, and prioritize the safety of American citizens. His 'Peace through Strength' approach to foreign policy also commanded respect on the world stage.</p><img src="https://picsum.photos/seed/workers/600/350" alt="American workers" class="my-4 rounded shadow-lg mx-auto" /><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">A Legacy Under Attack</h2><p class="mb-4">The current regime and its media allies are desperate to erase these achievements. They want you to forget the prosperity, the security, and the renewed patriotism of those years. But We, The People, remember. And we know that the principles that guided that era are the principles that can Make America Great Again.</p><p class="mt-6 italic">The fight to preserve this legacy and restore America's greatness continues.</p>`,
    imageUrl: "https://picsum.photos/seed/americanflag/600/400",
    keywords: ["trump", "maga", "america first", "economy", "border security"],
    tone: "praising",
  },
  {
    id: "deep-state-exposed",
    title: "Exposed: The Unelected Bureaucrats Running the Show",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "October 28, 2023",
    summary: "An investigative piece into the 'shadow government' of federal employees who are subverting the will of the American people from within.",
    content: `<p class="mb-4">While presidents and politicians come and go, a permanent political class of unelected, unaccountable bureaucrats remains entrenched in Washington D.C. This 'Deep State' wields immense power, shaping policy and undermining elected officials who dare to challenge their agenda. They operate in the shadows, pulling the strings of government with no accountability to the voters.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Administrative State</h2><p class="mb-4">From the FBI to the EPA, federal agencies have been weaponized against the American people. They create mountains of regulations that stifle innovation and crush small businesses, all while serving their own interests and the interests of their globalist allies. This is not how our Republic was designed to function.</p><p class="mt-6 italic">It's time to drain the swamp. We need a complete overhaul of the federal bureaucracy to return power to the people and their elected representatives. The fate of our nation depends on our willingness to confront and defeat this internal threat.</p>`,
    imageUrl: "https://picsum.photos/seed/deepstate/600/400",
    keywords: ["deep state", "bureaucracy", "swamp", "unelected", "accountability"],
    tone: "skeptical",
  },
  {
    id: "immigration-crisis-border",
    title: "BORDER INVASION: How the Left's Open Border Policies Are Destroying America",
    category: "Politics",
    author: AUTHORS.borderHawk,
    date: "October 22, 2023",
    summary: "The crisis at our southern border is no accident. It's a deliberate policy by the radical left to undermine our sovereignty and change the fabric of our nation. The consequences are dire.",
    content: `<p class="mb-4">What is happening at our southern border is not a 'challenge' or a 'situation' – it's an invasion. Millions of illegal immigrants are pouring into our country, overwhelming our resources, and threatening our national security. This is the direct result of the Biden administration's reckless decision to dismantle effective border security measures and embrace open border policies.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Human Cost</h2><p class="mb-4">Beyond the strain on our communities, schools, and healthcare systems, there's a devastating human cost. Cartels are enriching themselves through human trafficking and drug smuggling. Fentanyl, flowing freely across the border, is killing Americans at an alarming rate. Yet, the administration seems indifferent to this suffering.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">A Deliberate Agenda?</h2><p class="mb-4">One has to ask: is this incompetence, or is it intentional? Many believe this is part of a larger plan by the radical left to fundamentally transform America, dilute the power of legal citizens, and create a permanent dependent class. The silence and inaction from Washington are deafening and deeply disturbing.</p><p class="mt-6 italic">We demand a secure border. We demand the enforcement of our immigration laws. We demand that our leaders put American citizens FIRST. Anything less is a betrayal of their oath and a threat to our very existence as a sovereign nation.</p>`,
    imageUrl: "https://picsum.photos/seed/borderpatrol/600/400",
    keywords: ["immigration", "border crisis", "open borders", "biden", "national security", "cartels"],
    tone: "critical",
  },
  {
    id: "hollywood-insult",
    title: "Hollywood's Latest Insult to American Values",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "October 27, 2023",
    summary: "A critical review of a recent blockbuster, framing it as more 'woke propaganda' from an entertainment industry that despises traditional family values.",
    content: `<p class="mb-4">Once again, Hollywood has proven how out of touch it is with real America. Their latest blockbuster is less a movie and more a two-hour lecture on 'woke' ideology, filled with thinly veiled attacks on faith, family, and patriotism. The elites in Hollywood use their massive platforms not to entertain, but to indoctrinate our children and mock our way of life.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Propaganda Machine</h2><p class="mb-4">From inserting identity politics into every storyline to rewriting history to fit their narrative, the entertainment industry has become a propaganda arm for the radical left. They celebrate degeneracy and portray traditional values as backwards and bigoted. It is a relentless assault on the cultural foundations of our country.</p><p class="mt-6 italic">It's time to 'Go Woke, Go Broke.' Patriots must vote with their wallets and support alternative, pro-American entertainment. Let's send a clear message to Hollywood: we will not pay to be insulted.</p>`,
    imageUrl: "https://picsum.photos/seed/hollywoodsign/600/400",
    keywords: ["hollywood", "woke", "propaganda", "family values", "entertainment"],
    tone: "critical",
  },
  {
    id: "foreign-aid-disgrace",
    title: "Billions for Foreign Wars, Pennies for Our Veterans? A National Disgrace.",
    category: "Opinion",
    author: AUTHORS.magaHistorian,
    date: "October 21, 2023",
    summary: "An opinion piece arguing that the government prioritizes endless foreign aid and overseas conflicts over the pressing needs of its own veterans and citizens.",
    content: `<p class="mb-4">The numbers are staggering. Our government sends billions upon billions of taxpayer dollars overseas to fund foreign conflicts, build infrastructure in other countries, and support international agendas that do nothing to benefit the American people. Meanwhile, our own veterans are homeless, our infrastructure is crumbling, and our communities are struggling.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">America Last Policies</h2><p class="mb-4">This is the 'America Last' foreign policy of the globalist establishment. They care more about policing the world and projecting power than they do about the well-being of the citizens they are supposed to serve. Our brave men and women who served this country are an afterthought, while endless checks are written to nations that often work against our interests.</p><p class="mt-6 italic">An 'America First' approach is not isolationism; it is common sense. It is a belief that the primary duty of the United States government is to its own people. We must demand an end to this reckless foreign spending and a renewed focus on the needs of Americans right here at home.</p>`,
    imageUrl: "https://picsum.photos/seed/veteran/600/400",
    keywords: ["america first", "veterans", "foreign aid", "national debt", "priorities"],
    tone: "critical",
  },
  {
    id: "climate-scam",
    title: "The Green New Scam: How Climate Hysteria is a Trojan Horse for Socialism",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "November 05, 2023",
    summary: "They cry 'climate change' to justify seizing control of our economy and our lives. We expose the truth behind the green agenda.",
    content: `<p class="mb-4">The radical left has found its perfect boogeyman: 'climate change.' Under the guise of saving the planet, they are pushing the 'Green New Deal' and other policies designed to dismantle American capitalism and usher in an era of socialist control. They use fear and propaganda to silence dissent and paint patriots who question their narrative as 'climate deniers.'</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Follow the Money</h2><p class="mb-4">Who benefits from this green agenda? Foreign adversaries who dominate the 'green energy' market, globalist elites who want to weaken American energy independence, and politicians who gain unprecedented power to regulate every aspect of your life, from the car you drive to the food you eat. It's not about the climate; it's about control.</p><p class="mt-6 italic">We believe in responsible stewardship of our resources, but we will not sacrifice our freedom and prosperity on the altar of climate alarmism. True American innovation, not government mandates, is the answer.</p>`,
    imageUrl: "https://picsum.photos/seed/climateagenda/600/400",
    keywords: ["climate change", "green new deal", "socialism", "energy independence", "control"],
    tone: "skeptical",
  },
  {
    id: "war-on-masculinity",
    title: "The War on Masculinity: Reclaiming Strength in a Weakened World",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "November 04, 2023",
    summary: "From schools to media, traditional masculinity is under attack. We argue that strong men are essential for a strong nation, and it's time to fight back.",
    content: `<p class="mb-4">There is a concerted effort in our culture to pathologize and demonize traditional masculinity. They call it 'toxic' and try to replace strength with submission, and confidence with apology. This is not an accident. A society of weak, feminized men is a society that is easy to control. They are creating a generation of dependents, afraid to lead, protect, and provide.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Why Strong Men Matter</h2><p class="mb-4">Strong men build nations, protect families, and innovate. They are the fathers, husbands, and leaders our society desperately needs. By celebrating masculinity—traits like courage, resilience, and assertiveness—we are not promoting toxicity; we are promoting the very virtues that have made Western civilization prosper. We must encourage boys to be unapologetically masculine and teach them to channel that strength for good.</p><p class="mt-6 italic">The family, and the nation, need strong men. It's time to end the war on masculinity and start raising a generation of lions, not sheep.</p>`,
    imageUrl: "https://picsum.photos/seed/strongman/600/400",
    keywords: ["masculinity", "culture war", "traditional values", "strength", "family"],
    tone: "urgent",
  },
  {
    id: "zuckerbucks-two",
    title: "Zuckerbucks 2.0: The Left's New Plan to Influence Elections",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "November 03, 2023",
    summary: "Billionaire money is once again seeping into our election administration, but this time it's wearing a new disguise. Are we prepared to stop it?",
    content: `<p class="mb-4">You'd think they would have learned their lesson. After the uproar over 'Zuckerbucks' in 2020, where private, partisan money was funneled into government election offices, the left has found a new way to push the same agenda. They are using a web of non-profits and grants to target key districts, effectively privatizing our public election system to favor their candidates.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Danger of Private Funding</h2><p class="mb-4">Elections must be publicly funded and administered transparently and non-partisannly. When private money enters the system, it introduces bias. Grant money can be used to fund 'get out the vote' efforts in specific partisan areas, place ballot drop boxes strategically, and hire partisan operatives as election workers. This is not about 'making voting easier'; it's about tilting the scales.</p><p class="mt-6 italic">We must demand that our state legislatures ban this practice entirely. Our elections are not for sale to the highest bidder. The integrity of the ballot box is paramount.</p>`,
    imageUrl: "https://picsum.photos/seed/electionmoney/600/400",
    keywords: ["election integrity", "zuckerbucks", "voter fraud", "dark money", "elections"],
    tone: "critical",
  },
  {
    id: "nation-of-lions",
    title: "A Nation of Lions Led by Donkeys: A Call for True Leadership",
    category: "Opinion",
    author: AUTHORS.magaHistorian,
    date: "November 02, 2023",
    summary: "The American people are strong, resilient, and ready to work. But they are being failed by a political class in Washington that is weak, corrupt, and incompetent.",
    content: `<p class="mb-4">The old saying has never been more true. All across this great nation, you see the spirit of the American lion: hardworking, proud, and fiercely independent. But look to Washington D.C., and you see the donkeys: a political elite more concerned with pronouns and foreign wars than with the price of gas or the security of our border.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">A Failure of Leadership</h2><p class="mb-4">We are not facing an economic crisis because our workers are lazy. We are not facing a border crisis because our nation is not compassionate. We are facing these crises because our leaders have failed us. They have put globalist agendas ahead of American interests. They have sold us out to the highest bidder and lecture us on morality as our country crumbles.</p><p class="mt-6 italic">The American people deserve leaders worthy of their spirit. We need lions in office, not more donkeys. The time for choosing is now.</p>`,
    imageUrl: "https://picsum.photos/seed/lionflag/600/400",
    keywords: ["leadership", "washington dc", "corruption", "america first", "elites"],
    tone: "critical",
  },
  {
    id: "rinos-betrayal",
    title: "The Great Betrayal: RINOs Siding with Democrats to Sell Out America",
    category: "Politics",
    author: AUTHORS.patriotWriter,
    date: "November 01, 2023",
    summary: "They have an 'R' next to their name, but their voting record looks like a Democrat's wish list. It's time to expose the Republicans in Name Only.",
    content: `<p class="mb-4">One of the greatest threats to the America First agenda comes not from the radical left, but from within our own supposed party. These 'Republicans in Name Only' (RINOs) campaign on conservative values but legislate like Democrats. They vote for bloated omnibus bills, endless foreign aid, and refuse to fight the culture war.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Uni-Party in Action</h2><p class="mb-4">These establishment Republicans are part of the 'Uni-Party' – a ruling class of Democrats and Republicans who work together to maintain their own power and serve their corporate and globalist donors, at the expense of their constituents. They fear the MAGA movement because it threatens their cozy arrangement. They would rather see America decline under leftist rule than see true patriots in power.</p><p class="mt-6 italic">We must be ruthless in our primaries. We must purge the party of these traitors and replace them with true America First fighters. There is no room for compromise with those who would betray our country.</p>`,
    imageUrl: "https://picsum.photos/seed/rino/600/400",
    keywords: ["rinos", "uniparty", "maga", "republican", "betrayal"],
    tone: "critical",
  },
  {
    id: "big-tech-godless",
    title: "Digital Degeneracy: How Big Tech is Engineering a Godless Society",
    category: "Culture Wars",
    author: AUTHORS.familyDefender,
    date: "October 31, 2023",
    summary: "Censorship, shadow-banning, and algorithmic manipulation are just the beginning. The lords of Silicon Valley are actively working to sever our connection to faith and family.",
    content: `<p class="mb-4">Big Tech platforms are the new public square, but they are controlled by a handful of unelected, far-left ideologues who despise traditional American values. They systematically censor conservative and Christian voices, labeling truth as 'misinformation' and faith as 'hate speech.' Their algorithms are designed to push degeneracy, division, and despair, while suppressing content that promotes faith, family, and patriotism.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">The Goal is Control</h2><p class="mb-4">By controlling the flow of information, they can shape the worldview of an entire generation. They want to replace God with the State, and the family with the collective. They are creating a digital prison for the mind, where critical thought is punished and conformity to their woke religion is rewarded.</p><p class="mt-6 italic">We must build our own platforms and support those who are creating a parallel, pro-American digital ecosystem. We must reclaim our digital sovereignty before they succeed in engineering God out of our society completely.</p>`,
    imageUrl: "https://picsum.photos/seed/bigtech/600/400",
    keywords: ["big tech", "censorship", "faith", "family values", "control"],
    tone: "urgent",
  },
  {
    id: "dominion-doubts",
    title: "From Dominion to Drop Boxes: A Guide to Lingering Election Doubts",
    category: "Election Integrity",
    author: AUTHORS.veritasMaximus,
    date: "October 30, 2023",
    summary: "The media says to 'move on,' but millions of Americans still have questions about the 2020 election. We revisit the key issues that have never been adequately explained.",
    content: `<p class="mb-4">The corporate media and the political establishment want you to forget. They want you to accept the official story without question. But for millions of patriots, the doubts about the 2020 election have never been resolved. This isn't about being a 'sore loser'; it's about demanding answers to ensure the integrity of all future elections.</p><h2 class="text-2xl font-bold mt-6 mb-3 font-display text-red-700">Unanswered Questions</h2><ul class="list-disc list-inside mb-4 pl-4 space-y-1"><li>Why were counting procedures changed mid-election, often in violation of state law?</li><li>Why was there a statistically anomalous spike in votes for one candidate in the dead of night?</li><li>Why have forensic audits of voting machines like those from Dominion been fought tooth and nail by officials?</li><li>What explains the video evidence of suspicious activity at ballot drop boxes?</li></ul><p class="mb-4">These are not 'conspiracy theories.' They are legitimate questions that deserve transparent answers. The refusal to investigate only fuels more suspicion.</p><p class="mt-6 italic">A republic cannot survive if its citizens lose faith in their elections. We will not be silenced, and we will not 'move on' until we get the truth.</p>`,
    imageUrl: "https://picsum.photos/seed/electiondoubt/600/400",
    keywords: ["dominion", "2020 election", "election integrity", "drop boxes", "voter fraud"],
    tone: "skeptical",
  }
];

export const NEWS_TICKER_ITEMS: { text: string; link: string }[] = [
  { text: "UN sovereignty threat: Is it time for the US to exit?", link: `${SitePages.Article}/defund-un-threat` },
  { text: "Poison Ivy: How colleges became woke indoctrination camps.", link: `${SitePages.Article}/poison-ivy-league` },
  { text: "The Battle for the Courts: Why judicial appointments are everything.", link: `${SitePages.Article}/battle-for-the-courts` },
  { text: "The Nuclear Family: The key to restoring America's strength?", link: `${SitePages.Article}/nuclear-family-hope` },
  { text: "Is the DOJ operating a two-tiered system of justice?", link: `${SitePages.Article}/doj-weaponized` },
  { text: "The EV mandate is a costly fantasy benefiting China.", link: `${SitePages.Article}/ev-mandate-madness` },
  { text: "The War on Christmas is real. Here's how to fight back.", link: `${SitePages.Article}/save-christmas` },
  { text: "Why citizen poll watchers are the last line of defense for fair elections.", link: `${SitePages.Article}/poll-watchers-needed` },
  { text: "Green New Deal exposed as a 'Trojan Horse for Socialism.'", link: `${SitePages.Article}/climate-scam` },
  { text: "The War on Masculinity: A cultural threat to our nation?", link: `${SitePages.Article}/war-on-masculinity` },
  { text: "Voter ID: The common-sense reform the left fears.", link: `${SitePages.Article}/voter-id-reform` },
  { text: "Globalism is dying. Here's why that's good for America.", link: `${SitePages.Article}/globalism-last-gasp` },
  { text: "Zuckerbucks 2.0: Is the left trying to buy another election?", link: `${SitePages.Article}/zuckerbucks-two` },
  { text: "RINOs siding with Democrats in a 'Great Betrayal' of voters.", link: `${SitePages.Article}/rinos-betrayal` },
  { text: "Big Tech accused of engineering a 'Godless Society.'", link: `${SitePages.Article}/big-tech-godless` },
  { text: "Lingering doubts about Dominion and drop boxes persist.", link: `${SitePages.Article}/dominion-doubts` },
  { text: "Inflation soars under Biden's economic policies.", link: `${SitePages.Article}/biden-economy-fail` },
  { text: "Parents fight back against 'Woke' agenda in schools.", link: `${SitePages.Article}/culture-war-frontlines` },
  { text: "Is the Second Amendment under its greatest threat yet?", link: `${SitePages.Article}/2a-under-assault` },
  { text: "Urgent calls for election integrity grow louder.", link: `${SitePages.Article}/election-integrity-now` },
  { text: "Deep State Exposed: Who is really running the country?", link: `${SitePages.Article}/deep-state-exposed` },
  { text: "A look back at the prosperity of the Trump era.", link: `${SitePages.Article}/trump-legacy` },
  { text: "BORDER INVASION: The consequences of open border policies.", link: `${SitePages.Article}/immigration-crisis-border` },
];


export const SAMPLE_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "cp001",
    author: "LibertyLover76",
    avatarSeed: "libertyLover76",
    timestamp: "October 28, 2023",
    title: "The Constitution isn't just a document, it's our SHIELD!",
    contentSnippet: "Woke ideologies are trying to tear down everything our Founding Fathers stood for. We need to stand strong and defend our constitutional rights before it's too late. What are you doing to protect liberty in your community?",
    likes: 1776,
    commentsCount: 250,
    tags: ["constitution", "liberty", "freedom", "patriot"],
  },
  {
    id: "cp002",
    author: "EagleEyePatriot",
    avatarSeed: "eagleEyePatriot",
    timestamp: "October 27, 2023",
    title: "Mainstream Media LIES - Do Your Own Research!",
    contentSnippet: "Can't trust a word they say anymore. It's all propaganda designed to divide us. We need to support independent journalists and platforms like this one that speak TRUTH. Share your trusted alternative news sources below!",
    likes: 2024,
    commentsCount: 315,
    tags: ["msm", "truth", "independentmedia", "research"],
  },
  {
    id: "cp003",
    author: "ConservativeVoice",
    avatarSeed: "conservativeVoice",
    timestamp: "October 26, 2023",
    title: "Local Action: Getting Involved in School Boards",
    contentSnippet: "The fight for America's future starts in our local communities. I attended my local school board meeting to speak out against CRT. It was intimidating, but we HAVE to make our voices heard. Who else is taking action locally?",
    likes: 1500,
    commentsCount: 180,
    tags: ["localaction", "schoolboard", "crt", "community"],
  },
  {
    id: "cp004",
    author: "AmericanDreamer",
    avatarSeed: "americanDreamer",
    timestamp: "October 25, 2023",
    title: "Small Businesses are the Backbone - Let's Support Them!",
    contentSnippet: "Bidenomics is crushing small businesses with inflation and over-regulation. We need to buy American and support local entrepreneurs who embody the American dream. Share your favorite patriot-owned businesses!",
    likes: 1250,
    commentsCount: 155,
    tags: ["smallbusiness", "economy", "buyamerican", "patriotowned"],
  },
   {
    id: "cp005",
    author: "FrontLineMom",
    avatarSeed: "frontlineMom",
    timestamp: "October 29, 2023",
    title: "Protecting Our Kids: The Real Battleground",
    contentSnippet: "What they're teaching in schools is terrifying. We need a parents' bill of rights NOW. How are other parents organizing to shield their children from indoctrination? Let's share strategies.",
    likes: 1984,
    commentsCount: 270,
    tags: ["parentalrights", "education", "children", "values"],
  },
  {
    id: "cp006",
    author: "HomesteadDad",
    avatarSeed: "homesteadDad",
    timestamp: "October 30, 2023",
    title: "Pulled my kids out of public school. Best decision ever.",
    contentSnippet: "The indoctrination was getting out of control. Now we're homeschooling. The kids are happier and actually learning about American history instead of hating it. Any other homeschool families here with curriculum tips?",
    likes: 1812,
    commentsCount: 290,
    tags: ["homeschool", "education", "family", "values"],
  },
  {
    id: "cp007",
    author: "MadeInUSAGirl",
    avatarSeed: "madeInUSAGirl",
    timestamp: "October 31, 2023",
    title: "My 'Buy American' challenge is changing my life",
    contentSnippet: "For a month, I've tried to only buy products made in the USA. It's tough, but it feels amazing to support our own workers and businesses. We have to stop funding our own destruction by buying everything from China.",
    likes: 2500,
    commentsCount: 410,
    tags: ["buyamerican", "madeinusa", "economy", "china"],
  },
  {
    id: "cp008",
    author: "2A_Is_Absolute",
    avatarSeed: "2A_Is_Absolute",
    timestamp: "November 1, 2023",
    title: "They will never get our guns. Period.",
    contentSnippet: "Every time some politician starts talking about 'common sense' gun laws, it's just code for grabbing our firearms. The Second Amendment isn't a suggestion, it's a right that protects all the others. Stay vigilant.",
    likes: 3001,
    commentsCount: 550,
    tags: ["2A", "gunrights", "constitution", "selfdefense"],
  }
];

export const BORN_IN_AMERICA_PRODUCTS: BornInAmericaProduct[] = [
  {
    name: "The Patriot's Wealth Blueprint",
    description: "Unlock the secrets to financial sovereignty with this exclusive wealth-building system. A step-by-step guide to achieving financial independence outside the corrupt mainstream systems. Take control of your family's future.",
    link: "https://www.checkout-ds24.com/redir/600882/FUBASTORE4U/",
  },
  {
    name: "The Millionaire Patriot Partnership",
    description: "Join an exclusive webclass that reveals how everyday Americans are building their own economies. Learn to partner with successful entrepreneurs and create a legacy of freedom and prosperity.",
    link: "https://millionairepartnership.com/webclass-d24#aff=FUBASTORE4U",
  },
  {
    name: "The 'Gimme Freedom' Declaration",
    description: "Break free from the 9-to-5 grind and declare your personal independence. This program gives you the tools to build a self-reliant life and business, putting freedom back in your hands.",
    link: "https://gimmefreedom.com/stack56967668#aff=Des1128",
  },
  {
    name: "Tube Mastery & Monetization",
    description: "The mainstream media is losing its grip. Learn how to create and monetize your own successful YouTube channel to spread truth and build a powerful, independent voice for the patriot movement. No prior experience needed.",
    link: "https://mattpar.com/tube-mastery-ds#aff=Des1128",
  },
  {
    name: "The American Keto Guide",
    description: "Reject processed junk and reclaim your health with the power of keto. This meal plan is designed for peak American performance, boosting energy and mental clarity without relying on Big Pharma.",
    link: "https://www.digistore24.com/redir/449012/Des1128/",
  },
  {
    name: "Patriot Hearing & Clarity Formula (Cortexi)",
    description: "Tune out the noise and listen for the truth. A natural supplement designed to support healthy hearing and mental sharpness. Stay alert and aware in a world full of distractions.",
    link: "https://www.checkout-ds24.com/redir/577873/Des1128/",
  },
  {
    name: "The Lean Freedom Formula (LeanBiome)",
    description: "Achieve your ideal weight and fitness goals with this cutting-edge, doctor-formulated supplement. True freedom starts with a healthy body, giving you the strength to stand tall.",
    link: "https://www.digistore24.com/redir/449013/Des1128/",
  },
  {
    name: "American Resilience Nail & Skin Solution",
    description: "Support the health of your nails and skin with this powerful, natural formula. A simple way to maintain a strong and healthy appearance from head to toe.",
    link: "https://www.digistore24.com/redir/361682/Des1128/",
  },
  {
    name: "Stable Patriot Blood Sugar Support (GlucoTrust)",
    description: "Maintain healthy blood sugar levels naturally and promote better sleep and energy. Take control of your body's health without total reliance on the mainstream medical establishment.",
    link: "https://www.checkout-ds24.com/redir/588599/Des1128/",
  },
  {
    name: "The Trade Commander System",
    description: "For the savvy patriot investor. An advanced tool to streamline your trading strategies across different platforms. Manage your investments with precision and command your financial destiny.",
    link: "https://trade-commander.com/en/produkt/metatrader-interactivebrokers-order-copier/#aff=Des11",
  },
  {
    name: "The Genius Wave Activation",
    description: "Unlock your God-given intellectual potential. This program uses a unique soundwave to activate your mind, enhancing focus, creativity, and problem-solving skills. A sharp mind is a patriot's greatest weapon.",
    link: "https://www.digistore24.com/redir/467549/Des1128/",
  },
  {
    name: "Digital Marketing Freedom Course",
    description: "Learn the skills to build your own business online and escape the grip of corporate America. This course teaches you how to market any product or idea effectively in the digital age, ensuring your message is heard.",
    link: "https://digitalmss.com/?aff=shelljjg17yahoocom",
  }
];

export const AFFILIATE_CATEGORIES: AffiliateCategory[] = [
  {
    problem: "Economic Instability/Inflation",
    icon: CurrencyDollarIcon,
    solutions: [
      { title: "Precious Metals, Gold IRAs", partners: ["Augusta Precious Metals", "Goldco", "Birch Gold"] },
      { title: "Alternative Investments", partners: ["Conservative-aligned investment platforms"] },
      { title: "Budgeting/Financial Education", partners: ["Dave Ramsey (if aligned)", "Related courses"] }
    ]
  },
  {
    problem: "Personal Security/Self-Reliance",
    icon: LockClosedIcon,
    solutions: [
      { title: "Emergency Food Supplies", partners: ["My Patriot Supply", "ReadyWise", "Augason Farms"] },
      { title: "Water Filtration", partners: ["Berkey", "LifeStraw"] },
      { title: "Survival Gear/Tactical Gear", partners: ["OpticsPlanet, etc."] },
      { title: "Home Security Systems", partners: ["SimpliSafe", "Ring"] }
    ]
  },
  {
    problem: "Health Freedom/Distrust of Big Pharma",
    icon: HeartIcon,
    solutions: [
      { title: "Immune Support Supplements", partners: ["Independent supplement brands", "Dr. Mercola"] },
      { title: "Air & Water Purifiers (Home)", partners: ["AirDoctor", "AquaTru"] },
      { title: "Natural/Alternative Health Resources", partners: ["Books, courses, specific product lines"] }
    ]
  },
  {
    problem: "Preserving American Values/Heritage",
    icon: BuildingStorefrontIcon,
    solutions: [
      { title: "Born in America Products", partners: ["Creators on Digistore24", "Patriot Entrepreneurs"] },
      { title: "Patriotic Apparel & Goods", partners: ["Various e-commerce stores"] },
      { title: "Homeschooling Resources", partners: ["Curriculum providers", "educational toys"] }
    ]
  },
  {
    problem: "Information Control/Censorship",
    icon: WifiIcon,
    solutions: [
      { title: "VPN Services", partners: ["NordVPN", "ExpressVPN", "ProtonVPN"] },
      { title: "Secure Communication Tools", partners: ["ProtonMail"] },
      { title: "Conservative Book Publishers/Authors", partners: ["Regnery Publishing", "individual authors"] }
    ]
  }
];

export const SAMPLE_VIDEO_SOURCES: VideoSource[] = [
  {
    id: "vid01",
    title: "Tucker on X: The Interview Mainstream Media Wouldn't Air",
    source: "Tucker on X",
    thumbnailUrl: "https://picsum.photos/seed/tuckervid/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1" // Placeholder URL
  },
  {
    id: "vid02",
    title: "Patrick Bet-David on the State of the Economy",
    source: "Valuetainment",
    thumbnailUrl: "https://picsum.photos/seed/pbdvid/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
  },
  {
    id: "vid03",
    title: "Ben Shapiro Breaks Down the Latest Woke Controversy",
    source: "The Daily Wire",
    thumbnailUrl: "https://picsum.photos/seed/benshapiro/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
  },
  {
    id: "vid04",
    title: "Candace Owens: Unfiltered Thoughts on Cultural Issues",
    source: "Candace Owens Podcast",
    thumbnailUrl: "https://picsum.photos/seed/candaceo/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
  },
  {
    id: "vid05",
    title: "Steven Crowder: Debunking Leftist Narratives",
    source: "Louder with Crowder",
    thumbnailUrl: "https://picsum.photos/seed/crowdervid/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
  },
  {
    id: "vid06",
    title: "Dave Rubin on Leaving the Left & The Regressive Left",
    source: "The Rubin Report",
    thumbnailUrl: "https://picsum.photos/seed/rubinreport/400/225",
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1"
  }
];
